[package]
distribution = "2201.10.0"
org = "xlibb"
name = "pdfbox"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["pdfbox"]
icon = "icon.png"
repository = "https://github.com/xlibb/module-pdfbox"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.lib.pdfbox"
artifactId = "pdfbox-native"
version = "@toml.version@"
path = "../native/build/libs/pdfbox-native-@project.version@.jar"

[[platform.java17.dependency]]
groupId = "org.apache.pdfbox"
artifactId = "pdfbox"
version = "@pdfbox.version@"

[[platform.java17.dependency]]
groupId = "org.apache.pdfbox"
artifactId = "fontbox"
version = "@pdfbox.version@"
