name: Pull Request

on: pull_request

jobs:
    ubuntu-build:
        name: Build on Ubuntu
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v1

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    distribution: 'temurin'
                    java-version: 17.0.7

            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew
                
            -   name: Build the Package
                env:
                    packageUser: ${{ github.actor }}
                    packagePAT: ${{ secrets.GITHUB_TOKEN }}
                run: ./gradlew build --no-daemon --scan

            -   name: Generate Codecov Report
                uses: codecov/codecov-action@v3
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
